import type { Metadata } from "next";
import {Inter } from "next/font/google";
import "./global.css";
import { APPNAME, SERVER_URL } from "@/lib/constants";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: {
    template:`%s | Prostore`,
    default: APPNAME,
  },
  description: "Generated by create next app",
  metadataBase: new URL(SERVER_URL)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${interSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
